=== ksngo/xml/a_Validate/a2_schemas/schemaDoc4.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
        xmlns:contacts="http://www.example.com/contacts" 
        targetNamespace="http://www.example.com/contacts" 
        elementFormDefault="qualified">
    <element name="contacts">
        <complexType>
            <sequence>
                <element name="contact" minOccurs="0" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <!--  NameType is created below globally-->
                            <element name="name" type="contacts:NameType" />
                            <!--  LocationType is created below globally-->
                            <element name="location" type="contacts:LocationType" />
                            <element name="phone">
                                <complexType>
                                    <simpleContent>
                                        <extension base="string">
                                            <attribute name="kind" type="string" default="Home" />
                                        </extension>
                                    </simpleContent>
                                </complexType>
                            </element>
                            <!-- KnowsType is created below globally -->
                            <element name="knows" type="contacts:KnowsType" />
                            <!-- DescriptionType is created below globally -->
                            <element name="description" type="contacts:DescriptionType" />
                        </sequence>
                    </complexType>
                </element>
            </sequence>
            <attributeGroup ref="contacts:ContactAttributes" />
        </complexType>
    </element>
    <attributeGroup name="ContactAttributes">
        <attribute name="version" type="string" fixed="1.0" />
        <attribute name="source" type="string" />
    </attributeGroup>

    <attribute name="title" type="string" />
    <!--  NameType created here-->
    <complexType name="NameType">
        <group ref="contacts:NameGroup" />
    </complexType>
    <group name="NameGroup">
        <sequence>
            <element name="first" type="string" minOccurs="1" maxOccurs="unbounded" />
            <element name="middle" type="string" minOccurs="0" maxOccurs="1" />
            <element name="last" type="string" />
        </sequence>
    </group>
    <!--  LocationType created here-->
    <complexType name="LocationType">
        <choice minOccurs="0" maxOccurs="unbounded">
            <element name="address" type="string" />
            <sequence>
                <element name="latitude" type="string" />
                <element name="longitude" type="string" />
            </sequence>
        </choice>
    </complexType>
    <!-- KnowsType created here -->
    <complexType name="KnowsType"></complexType>
    <!-- DescriptionType created here -->
    <complexType name="DescriptionType" mixed="true">
        <choice minOccurs="0" maxOccurs="unbounded">
            <element name="em" type="string" />
            <element name="strong" type="string" />
            <element name="br" type="string" />
        </choice>
    </complexType>
</schema>

=== ksngo/xml/a_Validate/a2_schemas/b.xml
<?xml version="1.0"?>
<contacts xmlns="http://www.example.com/contacts" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.example.com/contacts schemaDoc4.xsd" 
    source="Beginning XML 5E" 
    version="1.0"
    >
    <contact>
        <name>
            <first>Joseph</first>
            <first>John</first>
            <last>Fawcett</last>
        </name>
        <location>
            <address>Exeter, UK</address>
            <latitude>50.7218</latitude>
            <longitude>-3.533617</longitude>
        </location>
        <phone kind="Home">001-234-567-8910</phone>
        <knows />
        <description>
            Joseph is a developer and author for Beginning XML
            <em>5th edition</em>
            .
            <br />
            Joseph
            <strong>loves</strong>
            XML!
        </description>
    </contact>
    <contact>
        <name>
            <first>Liam</first>
            <last>Quin</last>
        </name>
        <location>
            <address>Ontario, Canada</address>
        </location>
        <phone>+1 613 476 8769</phone>
        <knows />
        <description>XML Activity Lead at W3C</description>
    </contact>
</contacts>
