=== ksngo/xml/a_Validate/a3_schematron/schemeWithSchematronRules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
    xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xmlns:sch="http://www.ascc.net/xml/schematron" 
    elementFormDefault="qualified">
    <!-- schematron namespace sch -->
    <xs:element name="library">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="book" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="book">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title" />
                <xs:element ref="authors" />
                <xs:element ref="characters" />
                <xs:element ref="description" />
            </xs:sequence>
            <xs:attribute name="genre" use="required" />
            <xs:attribute name="id" use="required" type="xs:token" />
            <xs:attribute name="publishedDate" use="required" type="xs:gYear" />
        </xs:complexType>
    </xs:element>
    <xs:element name="title" type="xs:string" />
    <xs:element name="authors">
        <!-- embed schematron patterns inside XML Schema annotation and appinfo -->
        <xs:annotation>
            <xs:appinfo>
                <!-- start of schematron patterns -->
                <sch:pattern id="authors">
                    <!-- the rule context refers to the Xpath so when it encounters <authors>, the rule shall be tested -->
                    <sch:rule context="authors">
                        <!-- testing attribute count for <authors> to be equal number of <author>-->
                        <sch:assert test="@count = count(author)">
     The count attribute must equal the number of author elements.</sch:assert>
                    </sch:rule>
                </sch:pattern>
                <!-- end of schematron patterns -->
            </xs:appinfo>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="author" />
            </xs:sequence>
            <xs:attribute name="count" use="required" type="xs:integer" />
        </xs:complexType>
    </xs:element>
    <xs:element name="author">
        <xs:complexType mixed="true">
            <xs:attribute name="id" use="required" type="xs:token" />
        </xs:complexType>
    </xs:element>
    <xs:element name="characters">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="character" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="character">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name" />
                <xs:element ref="description" />
            </xs:sequence>
            <xs:attribute name="id" use="required" type="xs:token" />
        </xs:complexType>
    </xs:element>
    <xs:element name="name" type="xs:string" />
    <xs:element name="description" type="xs:string" />
</xs:schema>

=== ksngo/xml/a_Validate/a3_schematron/a.xml
<library
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="schemeWithSchematronRules.xsd"
>
<!-- xsi ==> xml schema instance -->
<!-- create xsi name space pointing to XMLSchema-instance, noNamespaceSchemaLocation attribute is declared with namespace xsi.-->
<!-- schemaLocation contains namespace-location pair -->
<!-- use noNamespaceSchemaLocation attribute as schemeWithSchematronRules.xsd has no targetNamespace(<schema targetnamespace="http://www.example.com/name >" -->
    <book id="ACMAS-20" publishedDate="1920" genre="Detective Fiction">
        <title>The Mysterious Affair at Styles</title>
        <authors count="1">
            <author id="AC">Agatha Christie</author>
        </authors>
        <characters>
            <character id="HP">
                <name>Hercule Poirot</name>
                <description>A former Belgian detective,
     now a private investigator.</description>
            </character>
            <character id="JJ">
                <name>James Japp</name>
                <description>A detective from London’s
     Scotland Yard.</description>
            </character>
            <character id="AH">
                <name>Arthur Hastings</name>
                <description>The narrator of the tale
     and an old friend of Poirot.</description>
            </character>
            <character id="AI">
                <name>Alfred Inglethorpe</name>
                <description>The new husband of Emily Cavendish,
     who is disliked by her family.</description>
            </character>
        </characters>
        <description>Emily Cavendish, a wealthy widow,
     marries again to Alfred Inglethorp.
     One night she is found poisoned and
     Alfred immediately becomes the main suspect.</description>
    </book>
    <book id="EGOSC-77" publishedDate="1977" genre="Science Fiction">
        <title>Ender’s Game</title>
        <authors count="1">
            <author id="OSC">Orson Scott Card</author>
        </authors>
        <characters>
            <character id="AW">
                <name>Andrew “Ender" Wiggin</name>
                <description>A young boy
 who is selected for Battle School following an incident
 with a local bully.</description>
            </character>
            <character id="MR">
                <name>Mazer Rackham</name>
                <description>A hero from the earlier Formic wars.</description>
            </character>
        </characters>
        <description>Earth is at war with an alien species known as Formics
 which nearly succeeded in destroying the human race.
 Ender is unwittingly thrust into combat against
 them.</description>
    </book>
</library>
